### ISSUE TITLE
WASAPI samplerate by track

### ISSUE THREAD

**Issue by mmar22** [stsaz/fmedia#11]
Hi I test your sw on windows and seems play only same files as setup in control panel.
Please add switching samplerate to code to same as file played. Now show err

**Comment by mmar22** [comment]
c:\Users\marian\Downloads\fmedia>fmedia --dev=2 "p:\9_PUBLIC\_AUDIO_FILES\WAV\SINUS 24bit\1kHz@0dB_96kHz_24bit.wav"
fmedia v1.1 (win-x64)

#1 " - " p:\9_PUBLIC\_AUDIO_FILES\WAV\SINUS 24bit\1kHz@0dB_96kHz_24bit.wav 65.92 MB, 2:00.000 (11,520,000 samples), 4608 kbps, WAVE, 96000 Hz, int24, stereo

[......................................................................] 0:00 / 2:0008:43:43.123 :249c [error] soxr: *1:        unsupported PCM conversion: int24/2/96000/i -> int24/2/48000/i


When i change config in control pannel from 48 to 96k then this file plays. Any other not equal SR same trouble.

**Comment by stsaz** [comment]
Yes, it's a known problem - libsoxr (the module which fmedia uses to convert sample rates) can't convert from/to int24 (i.e. 24-bit integer) format.  I guess we should file a feature request to its developers, but I still didn't pay much attention to this.  If you have time, you can ask the authors to add int24 support (libsoxr page is here: https://sourceforge.net/projects/soxr/).  Or I will try to implement this by myself in one of the next releases of fmedia.

Anyway, to overcome this issue use `--format=int16` - this tells fmedia to use int16 format, which works well with sample rate conversion.

**Comment by mmar22** [comment]
Sorry , but i need no conversion, i need switch dac to new samplerate same as file, because support it.
WASAPI is exactly for this purpose and bitperfect playback.
And too need 24bits btw. for wavdop DSD.

**Comment by stsaz** [comment]
WASAPI can operate in 2 different modes: shared and exclusive.
By default fmedia uses shared mode.  This is what you configure in Audio properties in Windows.  In this mode all audio is converted to this format internally by Windows.
In exclusive mode all other apps can't work while fmedia is exclusively holding access to the device.  In this mode you can avoid sample rate conversion if the file format is supported by your device.

So, you either need to use exclusive mode, or set int24/96k format in Windows settings for shared mode.  Otherwise there will be a conversion.

To set exclusive mode for playback open fmedia.conf and set `exclusive_mode 2` in `mod_conf "wasapi.out"` section:

```
mod_conf "wasapi.out" {
...
	exclusive_mode 2
```

**Comment by mmar22** [comment]
OMG Simon sorry i try exmode 1 and not work. 2 work fine thanks.
