### ISSUE TITLE
fmedia CLI - Show Buffer Progress in CLI

### ISSUE THREAD

**Issue by hl2guide** [stsaz/fmedia#17]
Please consider showing the buffer point on CLI progress bars (playback).

Maybe an opt-in setting (isShowBufferInProgress):
= for played
. for unplayed
_ for buffer

e.g

`[=============______........................]`

**Comment by stsaz** [comment]
Due to the fact that this progress bar shows seconds of audio, while playback buffer is 500msec by default - the bufferred data will always stay just one single `_` character:
`[=============_........................]`

I can only imagine this can be useful if you set huge playback buffer size (tens of seconds?) - but why would you do that?

**Comment by hl2guide** [comment]
On an old laptop I use I noticed delayed playback for HQ FLAC files.

I noticed that the average transfer rate for the network connection is about 6MB/s.

Maybe a "Buffering" status would be useful for old/slow connections?

**Comment by stsaz** [comment]
I'll think about this - I'm not currently sure whether it will make sense to try to reflect the amount of total downloaded and uncompressed data in audio progress bar.  I don't think it will ever be larger than 1 character (but I'll try to run some tests).
