### ISSUE TITLE
Unexpected list-dev results

### ISSUE THREAD

**Issue by johnyradio** [stsaz/fmedia#38]
getting unexpected results. Tried first as non-root, then as root:
```
$ fmedia --list-dev
fmedia v1.13 (linux-amd64)
10:38:08.736 :773 [error] (null): ffpulse_init(): Connection refused
[johny@myegg ~]$ su
Password: 
[root@myegg johny]# fmedia --list-dev
fmedia v1.13 (linux-amd64)
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
10:38:18.269 :778 [error] (null): ffpulse_init(): Connection refused
```

**Comment by stsaz** [comment]
Interesting...
Does other audio software work via Pulse Audio on your system?
Try to google `pa_context_connect connection refused` - it seems like some kind of PA configuration issue.

Anyway, you can disable Pulse Audio output in fmedia and use ALSA.
Read `Linux: use ALSA rather than Pulse Audio` section in `doc/tips.md` file.

And from my side: I'll try to fix the code so PA error won't affect ALSA input device list.

**Comment by johnyradio** [comment]
hi, thx. i don't understand all of this, but i got QJackRcd working with QJackCtl. 
Glad to know fmedia doesn't requre Pulse, as i prefer to run my OS without Pulse. 
i removed fmedia, but glad to run any tests you want, that don't require pulse.

**Comment by stsaz** [comment]
Since v1.15 --list-dev will show ALSA recording devices even if Pulse Audio is not installed
