### ISSUE TITLE
Need help with compilation for Fedora 18 i386

### ISSUE THREAD

**Issue by egalion** [stsaz/fmedia#4]
Hello, 

the precompiled binary doesn't work for me, because it looks like it has been compiled on a system with newer version of the C library. System update is not an option for, because I intend to use fmedia on an OLPC, for which the last OS version is Fedora 18.

I am trying to compile the supporting libraries from here 

https://github.com/stsaz/ff-3pt

but I get "No rule to make target"

What parameters should I use with the "make" command exactly?

**Comment by stsaz** [comment]
Hello!
It's not easy to re-build the whole ff-3pt package, because you'll have to manually download the official source code for each library, unpack, apply patches and run make as README file suggests.

Anyway, can you provide details why fmedia doesn't work on your system?  What error is printed in terminal?  Also, please look at what 'ldd' tool shows and see if there's a missing dependency somewhere.

Also, if you can figure out what symbol from libc causes the problem, we can try to solve the issue by updating the code so it won't require this symbol.

**Comment by egalion** [comment]
It gives me:

"/lib/libc.so.6: version `GLIBC_2.17` not found (required by  PATH/fmedia-0/core.so)"

When I do: 

sudo yum provides libc.so.6

I get a message that it is provided by the package

glibc-2.16-34.olpc.0.fc18.i686

which is obviously an older version of the C library

**Comment by stsaz** [comment]
Using "objdump -T" I've figured out that core.so and ogg.so are both using clock_gettime() from GLIBC_2.17.  So you'll have to re-build those 2 modules by yourself.

"man clock_gettime" says:
Link with -lrt (only for glibc versions before 2.17).

[makerules-glibc216.txt](https://github.com/stsaz/fmedia/files/1202495/makerules-glibc216.txt)

Apply this .patch file and run "make core.so", then "make ogg.so" from fmedia/ source directory.  It's unlikely that you need to re-build ff-3pt, so just use the binary files (download those from github).  However, there may be gcc compilation errors because I didn't test my code on an older compiler.

I hope this helps.

**Comment by stsaz** [comment]
@egalion Any success on building the modules?  Do you need help with that?

**Comment by egalion** [comment]
Hello, I tried the patch back in August, but I couldn't get it to work I have been busy doing other things since then, so haven't dealt with it. I will probably try it next week and will write again with the details.
