### ISSUE TITLE
Erro in FMEDIA for WINXP

### ISSUE THREAD

**Issue by kekelmer** [stsaz/fmedia#67]
I'm sorry my english.
FMEDIA Version: fmedia-1.15-win-x86
OS: WindowsXP
When trying to make a recording, the following message appears:

C:\fmedia2>fmedia --record --dev-loopback=0 -o rec.wav
fmedia v1.15 (win-x86)
08:58:28.140 :634 [error] wasapi: *2:   opening device #0: CoCreateInstance: (80
040154) Classe não registrada , format:int16/44100/2, excl:0
08:58:28.140 :634 [error] wasapi: *1:   opening device #0: CoCreateInstance: (80
040154) Classe não registrada , format:int16/44100/2, excl:0

**Comment by stsaz** [comment]
Hi!  Recording in Loopback Mode is a WASAPI-only feature.  And there is no WASAPI on Windows XP.  You should upgrade your Windows at least to Vista if you want this functionality.

Otherwise, if you want fmedia to play and record in Windows XP you should order fmedia to use Direct Sound.  You can do it by manually editing `fmedia.conf` file: https://github.com/stsaz/fmedia/blob/master/doc/troubleshooting.md
