### ISSUE TITLE
Suggestions: winget install fmedia

### ISSUE THREAD

**Issue by oklokl** [stsaz/fmedia#87]
windows10~11 cmd
`winget search "fmedia"`

`winget install "fmedia" --id "stsaz.fmedia" -s "winget" --accept-package-agreements`

`winget` I wish there was a version to install as well. 

https://en.wikipedia.org/wiki/Windows_Package_Manager

thank you.
:)

**Comment by stsaz** [comment]
Although it would be nice to have an option to install via winget (I guess), it currently supports installers (.exe, etc.) only.  But fmedia package is just a portable .zip archive.  I should create .exe installer first and only then fmedia can be registered in winget directory.  I'm also not sure that MS allows installing (i.e. just unpacking) portable software via winget.  Also there is a concern about licensing, because fmedia uses 3rd party libraries with different licenses, and I don't know (and I don't want to know) much about this stuff...  So it's not that simple.

**Comment by oklokl** [comment]
https://github.com/microsoft/winget-cli 
Very attractive. There seems to be no licensing problem. Github support.
I will politely ask the noble developer
My heart wishing you would..
I'm stuck with this process. it's so easy
:)

And I use the command below.
my install Tip (cmd) I'm using drag-copy.

```
echo Download
powershell.exe -Command "& {Invoke-WebRequest -OutFile $env:ProgramFiles\fmedia\fmedia-1.29-win-x64.zip -Uri "https://github.com/stsaz/fmedia/releases/download/v1.29/fmedia-1.29-win-x64.zip"}
tar -zxvf "%ProgramFiles%\fmedia\fmedia-1.29-win-x64.zip" -C "%ProgramFiles%"
"%ProgramFiles%\fmedia\fmedia.exe" --install

or

echo Remove 
"%ProgramFiles%\fmedia\fmedia.exe" --uninstall
rmdir "%ProgramFiles%\fmedia\." /s /q
```
I'm not a developer, so the command may be slightly wrong.
I work fine.
